"""
Django settings for Django_RestAPI_Project project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path
import logging
from logging.handlers import RotatingFileHandler
from datetime import date

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ------------------------------
# 🚀 LOGGING CONFIGURATION
# ------------------------------
logs_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'logs')

current_year = date.today().strftime('%Y')
current_month = date.today().strftime('%m')

year_month_dir = os.path.join(logs_dir, current_year, current_month)
os.makedirs(year_month_dir, exist_ok=True)

log_file = os.path.join(year_month_dir, f'{date.today()}.log')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': log_file,
            'formatter': 'verbose',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}


# ------------------------------
# 🔐 SECURITY SETTINGS
# ------------------------------
SECRET_KEY = 'django-insecure-!yr#%z_^tp_z_2fi!6+_d@a=vp*e5+zt5khp*ojuj(^p&ij5r2'
DEBUG = True

# REQUIRED for Angular access
ALLOWED_HOSTS = ['*']


# ------------------------------
# 📦 INSTALLED APPS
# ------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'corsheaders',
    'rest_framework',

    # Local app
    'api',
]


# ------------------------------
# ⚙️ MIDDLEWARE (ORDER FIXED)
# ------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',   # MUST BE FIRST
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ------------------------------
# 🌐 CORS & CSRF SETTINGS
# ------------------------------

# Allow Angular frontend
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'x-csrftoken',
    'accept',
    'origin',
]

CORS_EXPOSE_HEADERS = ['Content-Type', 'Authorization']

# Allow Angular apps only
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:4200',
    'http://127.0.0.1:4200'
]


# ------------------------------
# 🔗 URLS / TEMPLATES / WSGI
# ------------------------------
ROOT_URLCONF = 'Django_RestAPI_Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django_RestAPI_Project.wsgi.application'


# ------------------------------
# 🗄 DATABASE CONFIG (SQLite)
# ------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

APPEND_SLASH = False


# ------------------------------
# 🔐 PASSWORD VALIDATION
# ------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ------------------------------
# 🌍 INTERNATIONALIZATION
# ------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ------------------------------
# 🖼 STATIC FILES
# ------------------------------
STATIC_URL = 'static/'


# ------------------------------
# 🔑 DEFAULT PRIMARY KEY
# ------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
